apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-vault
  name: edgex-vault
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-vault
    spec:
      containers:
      - image: edgexfoundry/docker-edgex-vault:1.0.0-dev
        name: edgex-vault
        ports:
        - containerPort: 8200
        resources: {}
        volumeMounts:
        - mountPath: /vault/config
          name: vault-config
        - mountPath: /vault/file
          name: vault-file
        - mountPath: /vault/logs
          name: vault-logs
        env: 
          - name: VAULT_ADDR
            value: https://edgex-vault:8200
          - name: AULT_CONFIG_DIR
            value: /vault/config
          - name: VAULT_UI
            value: "true"
      restartPolicy: Always
      volumes:
      - name: vault-config
        hostPath:
          path: /vault/config
      - name: vault-file
        hostPath:
          path: /vault/file
      - name: vault-logs
        hostPath:
          path: /vault/logs
status: {}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: edgex-vault-worker
  labels:
    io.kompose.service: edgex-vault-worker
spec:
  template:
    metadata:
      labels:
        io.kompose.service: edgex-vault-worker
    spec: 
      containers: 
      - image: edgexfoundry/docker-edgex-vault-worker-go:1.0.0
        name: edgex-vault-worker
        imagePullPolicy: IfNotPresent
        volumeMounts: 
        - mountPath: /vault/config
          name: vault-config
        command: ["/edgex/edgex-vault-worker"]
        args: ["--init=true", "--debug=false", "--wait=10", "--insureskipverify=false"]
      volumes:
      - name: vault-config
        hostPath:
          path: /vault/config
      restartPolicy: OnFailure
