docker pull    edgexfoundry/docker-edgex-volume:1.0.0
docker pull    consul:1.3.1
docker pull    edgexfoundry/docker-core-config-seed-go:1.0.0
docker pull    edgexfoundry/docker-edgex-vault:1.0.0
docker pull    edgexfoundry/docker-edgex-vault-worker-go:1.0.0
docker pull    postgres:9.6
docker pull    kong:1.0.3
docker pull    kong:1.0.3
docker pull    edgexfoundry/docker-edgex-proxy-go:1.0.0
docker pull    edgexfoundry/docker-edgex-mongo:1.0.1
docker pull    edgexfoundry/docker-support-logging-go:1.0.1
docker pull    edgexfoundry/docker-sys-mgmt-agent-go:1.0.1
docker pull    edgexfoundry/docker-support-notifications-go:1.0.1
docker pull    edgexfoundry/docker-core-metadata-go:1.0.1
docker pull    edgexfoundry/docker-core-data-go:1.0.1
docker pull    edgexfoundry/docker-core-command-go:1.0.1
docker pull    edgexfoundry/docker-support-scheduler-go:1.0.1
docker pull    edgexfoundry/docker-export-client-go:1.0.1
docker pull    edgexfoundry/docker-export-distro-go:1.0.1
docker pull    edgexfoundry/docker-support-rulesengine:1.0.0
docker pull    edgexfoundry/docker-device-virtual-go:1.0.0
docker pull    edgexfoundry/docker-edgex-ui-go:1.0.0
docker pull    portainer/portainer
