apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-ui-go
  name: edgex-ui-go
spec:
  type: NodePort
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
    nodePort: 30001
  selector:
    io.kompose.service: edgex-ui-go
status:
  loadBalancer: {}
